language: java

matrix:
  include:
    - env: TARGET_AP_SERVER=tomcat90
      jdk: openjdk11

cache:
  directories:
    - "$HOME/.m2"

install: true

env:
  global:
  - secure: OYpjRGu1vnh+yrWqdpaF1nWAzshvlFzh9frQGZv51PCrB+xnwY6SLiwtrlNZ9NKp60Buoxf3YySAml2xG86Y0gUCVjUsFlWg0mBFs1Hvnv6lxUVla6ZjiQ+C9wSavjky6jPbGrBjHd2uXvdUnElMzJc7j6Czm6BigmAaivPfwE0=
  - secure: n8R+jUI2M/SY3pfiVOP95jLbkMXSIrAVhJ6ttTyr9k9OpLdIiP0LJ/Ccv/lNawx0TBlbApcZsc+fh3YZC5QJOl4+2pT9yc7+nULv8LlWoDVjWy+31rD6UJsxgGvADks1gs8SYvW2oHP2vNd8GUpNG6W3hmBkQm80wi6ssAxysZM=

addons:
  sonarcloud:
    organization: "jxshin"
    token:
      secure: "fAqgo0Oai7oVpphmTtzOJWYFg4+kG5Js9ZSnF7roac0q2feYedERpdw1LTpzTl1cd1SS4R1KJUh/XTAxOGyK4nWtnBBI1R+X0qRi6vBCfdWsyeXsLi6G5kG4SPtNH4xYIjzwPh1nDz+w/OJhw7b+gg0Nh31DPSbtir7Px7yQ/55S05xRlJ66UxUN/w+Z0z/KHTfna7iXy83winDq9EMqDoKbg/VV2IvNmN1B5oWszS+JWsygBDUPLkNCiLAJ7hR7CwH2a40ZCokgjZ4J00LqHDv/B1O6y9sAsvHspEnr5aomZ4W2SfLV4f3S4Th2vf2yevLEFfEjEfZLN5Ldx2O32xR17Z4CW7dA6AS24OPJkqyKleMIeybwpNOPBOpEoF7H+eVKt5kzCE2Fg13NieyQDpkUREkOYddowbcCCzFNobg+1dTzkb3nYy2Iyt1O7b2VoT+sQhw3Elal1bYmXmsVFeXqmylVu19nldQH0gCwXdb/CL+SUKMcoqDgf4Cs3CMaRbbZKKuFtB7LEeMaHDNlTbqkaHXtfFJIz4lLpHkbNLT+SiQ3aRaZtevUtJNcHPxWZi0ngX3DxC/qi2THBwmjgRQx3EJpHmh9muLhNx6kqCvTfxqWuchODWu3aNejExd3N1Q6zXUuuMkg9cF69z0sGI0UknyDSM4X9L97f6KaEjo="

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=jxshin_jpetstore-6

