language: java

matrix:
  include:
    - env: TARGET_AP_SERVER=tomcat90
      jdk: openjdk11

cache:
  directories:
    - "$HOME/.m2"

install: true

env:
  global:
  - secure: OYpjRGu1vnh+yrWqdpaF1nWAzshvlFzh9frQGZv51PCrB+xnwY6SLiwtrlNZ9NKp60Buoxf3YySAml2xG86Y0gUCVjUsFlWg0mBFs1Hvnv6lxUVla6ZjiQ+C9wSavjky6jPbGrBjHd2uXvdUnElMzJc7j6Czm6BigmAaivPfwE0=
  - secure: n8R+jUI2M/SY3pfiVOP95jLbkMXSIrAVhJ6ttTyr9k9OpLdIiP0LJ/Ccv/lNawx0TBlbApcZsc+fh3YZC5QJOl4+2pT9yc7+nULv8LlWoDVjWy+31rD6UJsxgGvADks1gs8SYvW2oHP2vNd8GUpNG6W3hmBkQm80wi6ssAxysZM=

addons:
  sonarcloud:
    organization: "jxshin"
    token:
      secure: "Qu3afLPV3nZW7tHhG2g86UiV3BIOi6/nK/6eGxMxbB3DgDezgyUfRFg2vpoD8LKX1aQvjf5VYYpeP71ExSYqpfdevEen/W1b40kH1Y6gq0CJ2W1gBL0sTgXZCfOQBZnRaU03QOXE8AQPXp+89J4hazJtzJkg+KxfJDUgqN2xuUKoNThP4WYksJns2n3sF2DyBT52rdvCchx83EMhLNJ4xxtp2Zz63qsqwRm2CQcKtpiLlPMCIgPw6u5ma5r4r+1RR+vXkQo0IQZAPHhb4VwmOPFcE9eNwQ9zsWf4Pmym/zq2NlLT/j4PU3G7n9r0sG/lkKdMMxCCScx4/jU+uB7HUukZ7lhCq5vz4NdupZ+WJD553qNHEM97D0JS/Oms+TW5d4mmuRDH71suctMf3wk682PQf95MBl2L/4XkYX6ReSCndEcfsUUTu9dFdFK1G0Cmwnc6CIwF53Y7RVTw7YiHAtFJxbddRPuW/ZHAw3yMSTJhqFvFOKUVIu25VmWJv6B1ZJNVVptuuXxFB+8wXrM468iCDqjyZ40HONZ1Xr6+1mZDevO95AcuCcCpUDmqFC66PwIOz4pWpy/geXS67TuK3ZNcRAkxrL+pbruRMmFNJkgvqdbNCEidcx4zwXAtpYSaUoyiz+voXDFEG6RGE3s/3rDp6s0OzfSDbwjasJLZgvk="

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

