language: java

matrix:
  include:
    - env: TARGET_AP_SERVER=tomcat90
      jdk: openjdk11

cache:
  directories:
    - "$HOME/.m2"

install: true

env:
  global:
  - secure: OYpjRGu1vnh+yrWqdpaF1nWAzshvlFzh9frQGZv51PCrB+xnwY6SLiwtrlNZ9NKp60Buoxf3YySAml2xG86Y0gUCVjUsFlWg0mBFs1Hvnv6lxUVla6ZjiQ+C9wSavjky6jPbGrBjHd2uXvdUnElMzJc7j6Czm6BigmAaivPfwE0=
  - secure: n8R+jUI2M/SY3pfiVOP95jLbkMXSIrAVhJ6ttTyr9k9OpLdIiP0LJ/Ccv/lNawx0TBlbApcZsc+fh3YZC5QJOl4+2pT9yc7+nULv8LlWoDVjWy+31rD6UJsxgGvADks1gs8SYvW2oHP2vNd8GUpNG6W3hmBkQm80wi6ssAxysZM=

addons:
  sonarcloud:
    organization: "jxshin"
    token:
      secure: "MwdF5lBGhFbyLbeDF2mhtAV8wxGtqubaGm9SaiIIm6YdrDdeUKnU0eZlbsh83S9DVVEvorOFRojWYl7F6VKXtSAHbYJOImdwpm3jpH2H7DK7ZYYiFagXJdEEjMKsdsPUIsAIDr4eg+it9nnPVockb9jtzZLIwig6iE5ozKTAJIuW+sJ853jYPHJOi5upbOxcekgeeofiM5P9eeq+N26UxWeTaHZMmeugH10nzOmHsI63P9ElwDhXI/Pc4kkAPcov7xd3lsW0frdFKR4gX7HIgp5gPWIV/6qh++bjg1XuwInO8YER8B7WUkAWVRwIRCUylEyv7R4EU5rm87bgmTJ0mPJr86zkjRjldTG92mnLxFPRwfabQPcRSN0Jczm9MUqZcgsxWNHb2zD7wdeGB+DCSFIAqpJWlH7bZHqr4kqKfabJzYR9sfO6lvmV39rIw0cD9tDysQKMDKBowMShW4kwwVjIsY4UTT5nmBJBLptPKz0yATOgeGJSVeO02TPKlEWIxImZovetrzMXJfP4BBBHPMc9fXakiEF3zUL2nz+vgRU47WmHIibliFIvI1p5lJ0UwowM0buymGZMas2KyuONf64zLHx+s8ilCj4s5rSnU1fyx9KSBPlyHBl4iWWkd6pk8dTH5zcSFD2OMlxL1DJeWB+m1zz3xONfSbSdV8Ohu/c="

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

